### ISSUE TITLE
[minor] Error handling

### ISSUE THREAD

**Issue by ale1313** [ThomyR73/ReactRickAndMortyApiChallenge#2]
Even if current error handling is correct, messages shown to user should be more specific about the current situation of the app, for example instead of an "404 Error: Not found", perhaps a better approach should be notifying the user about the current search not returning any result. The same applies to other kinds of error that an user could step into.

**Comment by ThomyR73** [comment]
issue solved on commit 522b8655849368cebb26432af0fdf7f8dcfca0a3
